; ---------------------------------------------------------------------------
; Sonic 1 Dynamic PLC Script - Generated by Sonic Triad Studio
; To be used with spritePiece Macro. Set SonicMappingsVer to 1 to use this DPLC script.
; ---------------------------------------------------------------------------
TailsDynPLC:	mappingsTable
		mappingsTableEntry.w	TailDPLC_Null
		mappingsTableEntry.w	TailDPLC_Stand1
		mappingsTableEntry.w	TailDPLC_Stand2
		mappingsTableEntry.w	TailDPLC_Stand3
		mappingsTableEntry.w	TailDPLC_LookUp
		mappingsTableEntry.w	TailDPLC_Idle1
		mappingsTableEntry.w	TailDPLC_Idle2
		mappingsTableEntry.w	TailDPLC_Idle3
		mappingsTableEntry.w	TailDPLC_Idle4
		mappingsTableEntry.w	TailDPLC_Walk11
		mappingsTableEntry.w	TailDPLC_Walk12
		mappingsTableEntry.w	TailDPLC_Walk13
		mappingsTableEntry.w	TailDPLC_Walk14
		mappingsTableEntry.w	TailDPLC_Walk15
		mappingsTableEntry.w	TailDPLC_Walk16
		mappingsTableEntry.w	TailDPLC_Walk17
		mappingsTableEntry.w	TailDPLC_Walk18
		mappingsTableEntry.w	TailDPLC_Walk21
		mappingsTableEntry.w	TailDPLC_Walk22
		mappingsTableEntry.w	TailDPLC_Walk23
		mappingsTableEntry.w	TailDPLC_Walk24
		mappingsTableEntry.w	TailDPLC_Walk25
		mappingsTableEntry.w	TailDPLC_Walk26
		mappingsTableEntry.w	TailDPLC_Walk27
		mappingsTableEntry.w	TailDPLC_Walk28
		mappingsTableEntry.w	TailDPLC_Walk31
		mappingsTableEntry.w	TailDPLC_Walk32
		mappingsTableEntry.w	TailDPLC_Walk33
		mappingsTableEntry.w	TailDPLC_Walk34
		mappingsTableEntry.w	TailDPLC_Walk35
		mappingsTableEntry.w	TailDPLC_Walk36
		mappingsTableEntry.w	TailDPLC_Walk37
		mappingsTableEntry.w	TailDPLC_Walk38
		mappingsTableEntry.w	TailDPLC_Walk41
		mappingsTableEntry.w	TailDPLC_Walk42
		mappingsTableEntry.w	TailDPLC_Walk43
		mappingsTableEntry.w	TailDPLC_Walk44
		mappingsTableEntry.w	TailDPLC_Walk45
		mappingsTableEntry.w	TailDPLC_Walk46
		mappingsTableEntry.w	TailDPLC_Walk47
		mappingsTableEntry.w	TailDPLC_Walk48
		mappingsTableEntry.w	TailDPLC_Run11
		mappingsTableEntry.w	TailDPLC_Run12
		mappingsTableEntry.w	TailDPLC_Run13
		mappingsTableEntry.w	TailDPLC_Run14
		mappingsTableEntry.w	TailDPLC_Run15
		mappingsTableEntry.w	TailDPLC_Run16
		mappingsTableEntry.w	TailDPLC_Run21
		mappingsTableEntry.w	TailDPLC_Run22
		mappingsTableEntry.w	TailDPLC_Run23
		mappingsTableEntry.w	TailDPLC_Run24
		mappingsTableEntry.w	TailDPLC_Run25
		mappingsTableEntry.w	TailDPLC_Run26
		mappingsTableEntry.w	TailDPLC_Run31
		mappingsTableEntry.w	TailDPLC_Run32
		mappingsTableEntry.w	TailDPLC_Run33
		mappingsTableEntry.w	TailDPLC_Run34
		mappingsTableEntry.w	TailDPLC_Run35
		mappingsTableEntry.w	TailDPLC_Run36
		mappingsTableEntry.w	TailDPLC_Run41
		mappingsTableEntry.w	TailDPLC_Run42
		mappingsTableEntry.w	TailDPLC_Run43
		mappingsTableEntry.w	TailDPLC_Run44
		mappingsTableEntry.w	TailDPLC_Run45
		mappingsTableEntry.w	TailDPLC_Run46
		mappingsTableEntry.w	TailDPLC_Roll1
		mappingsTableEntry.w	TailDPLC_Roll2
		mappingsTableEntry.w	TailDPLC_Roll3
		mappingsTableEntry.w	TailDPLC_Spring1
		mappingsTableEntry.w	TailDPLC_Spring2
		mappingsTableEntry.w	TailDPLC_Duck
		mappingsTableEntry.w	TailDPLC_Hurt
		mappingsTableEntry.w	TailDPLC_Death
		mappingsTableEntry.w	TailDPLC_Fly1
		mappingsTableEntry.w	TailDPLC_Fly2
		mappingsTableEntry.w	TailDPLC_Spindash1
		mappingsTableEntry.w	TailDPLC_Spindash2
		mappingsTableEntry.w	TailDPLC_Spindash3
		mappingsTableEntry.w	TailDPLC_Push1
		mappingsTableEntry.w	TailDPLC_Push2
		mappingsTableEntry.w	TailDPLC_Push3
		mappingsTableEntry.w	TailDPLC_Push4
		mappingsTableEntry.w	TailDPLC_Stop1
		mappingsTableEntry.w	TailDPLC_Stop2
		mappingsTableEntry.w	TailDPLC_Balance1
		mappingsTableEntry.w	TailDPLC_Balance2
		mappingsTableEntry.w	TailDPLC_WaterSlide
		mappingsTableEntry.w	TailDPLC_Hang1
		mappingsTableEntry.w	TailDPLC_Hang2
		mappingsTableEntry.w	TailDPLC_Float1
		mappingsTableEntry.w	TailDPLC_Float2
		mappingsTableEntry.w	TailDPLC_Float3
		mappingsTableEntry.w	TailDPLC_Float4
		mappingsTableEntry.w	TailDPLC_Float5
		mappingsTableEntry.w	TailDPLC_Float6
		mappingsTableEntry.w	TailDPLC_GetAir
		mappingsTableEntry.w	TailDPLC_FlyTired1
		mappingsTableEntry.w	TailDPLC_FlyTired2
		mappingsTableEntry.w	TailDPLC_Swim1
		mappingsTableEntry.w	TailDPLC_Swim2
		mappingsTableEntry.w	TailDPLC_Swim3
		mappingsTableEntry.w	TailDPLC_Swim4
		mappingsTableEntry.w	TailDPLC_Swim5
		mappingsTableEntry.w	TailDPLC_SwimTired1
		mappingsTableEntry.w	TailDPLC_SwimTired2
		mappingsTableEntry.w	TailDPLC_SwimTired3

TailDPLC_Null:	dplcHeader
TailDPLC_Null_End

TailDPLC_Stand1:	dplcHeader
	dplcEntry	$C, 0
TailDPLC_Stand1_End

TailDPLC_Stand2:	dplcHeader
	dplcEntry	6, $C
	dplcEntry	6, 6
TailDPLC_Stand2_End

TailDPLC_Stand3:	dplcHeader
	dplcEntry	6, $12
	dplcEntry	6, 6
TailDPLC_Stand3_End

TailDPLC_LookUp:	dplcHeader
	dplcEntry	6, $18
	dplcEntry	6, 6
TailDPLC_LookUp_End

TailDPLC_Idle1:	dplcHeader
	dplcEntry	$C, $1E
TailDPLC_Idle1_End

TailDPLC_Idle2:	dplcHeader
	dplcEntry	$C, $2A
TailDPLC_Idle2_End

TailDPLC_Idle3:	dplcHeader
	dplcEntry	$C, $36
TailDPLC_Idle3_End

TailDPLC_Idle4:	dplcHeader
	dplcEntry	6, $36
	dplcEntry	6, $42
TailDPLC_Idle4_End

TailDPLC_Walk11:	dplcHeader
	dplcEntry	6, $48
	dplcEntry	8, $4E
	dplcEntry	6, $98
TailDPLC_Walk11_End

TailDPLC_Walk12:	dplcHeader
	dplcEntry	6, $56
	dplcEntry	8, $5C
	dplcEntry	6, $9E
TailDPLC_Walk12_End

TailDPLC_Walk13:	dplcHeader
	dplcEntry	6, $64
	dplcEntry	6, $6A
	dplcEntry	6, $A4
TailDPLC_Walk13_End

TailDPLC_Walk14:	dplcHeader
	dplcEntry	6, $70
	dplcEntry	6, $76
	dplcEntry	6, $AA
TailDPLC_Walk14_End

TailDPLC_Walk15:	dplcHeader
	dplcEntry	6, $48
	dplcEntry	8, $7C
	dplcEntry	6, $98
TailDPLC_Walk15_End

TailDPLC_Walk16:	dplcHeader
	dplcEntry	6, $56
	dplcEntry	8, $84
	dplcEntry	6, $9E
TailDPLC_Walk16_End

TailDPLC_Walk17:	dplcHeader
	dplcEntry	6, $64
	dplcEntry	6, $8C
	dplcEntry	6, $A4
TailDPLC_Walk17_End

TailDPLC_Walk18:	dplcHeader
	dplcEntry	6, $70
	dplcEntry	6, $92
	dplcEntry	6, $AA
TailDPLC_Walk18_End

TailDPLC_Walk21:	dplcHeader
	dplcEntry	2, $B0
	dplcEntry	4, $B2
	dplcEntry	$C, $B6
TailDPLC_Walk21_End

TailDPLC_Walk22:	dplcHeader
	dplcEntry	4, $C2
	dplcEntry	$C, $C6
	dplcEntry	4, $D2
TailDPLC_Walk22_End

TailDPLC_Walk23:	dplcHeader
	dplcEntry	4, $D6
	dplcEntry	4, $DA
	dplcEntry	$C, $DE
TailDPLC_Walk23_End

TailDPLC_Walk24:	dplcHeader
	dplcEntry	2, $EA
	dplcEntry	$10, $EC
	dplcEntry	2, $FC
TailDPLC_Walk24_End

TailDPLC_Walk25:	dplcHeader
	dplcEntry	2, $B0
	dplcEntry	4, $B2
	dplcEntry	$C, $FE
TailDPLC_Walk25_End

TailDPLC_Walk26:	dplcHeader
	dplcEntry	4, $C2
	dplcEntry	$C, $10A
	dplcEntry	4, $116
TailDPLC_Walk26_End

TailDPLC_Walk27:	dplcHeader
	dplcEntry	4, $D6
	dplcEntry	4, $DA
	dplcEntry	$C, $11A
TailDPLC_Walk27_End

TailDPLC_Walk28:	dplcHeader
	dplcEntry	2, $EA
	dplcEntry	$10, $126
	dplcEntry	2, $136
TailDPLC_Walk28_End

TailDPLC_Walk31:	dplcHeader
	dplcEntry	8, $138
	dplcEntry	8, $140
	dplcEntry	8, $198
TailDPLC_Walk31_End

TailDPLC_Walk32:	dplcHeader
	dplcEntry	8, $148
	dplcEntry	8, $150
	dplcEntry	8, $1A0
TailDPLC_Walk32_End

TailDPLC_Walk33:	dplcHeader
	dplcEntry	8, $158
	dplcEntry	8, $160
	dplcEntry	8, $1A8
TailDPLC_Walk33_End

TailDPLC_Walk34:	dplcHeader
	dplcEntry	8, $168
	dplcEntry	8, $170
	dplcEntry	8, $4A4
TailDPLC_Walk34_End

TailDPLC_Walk35:	dplcHeader
	dplcEntry	8, $138
	dplcEntry	8, $178
	dplcEntry	8, $198
TailDPLC_Walk35_End

TailDPLC_Walk36:	dplcHeader
	dplcEntry	8, $148
	dplcEntry	8, $180
	dplcEntry	8, $1A0
TailDPLC_Walk36_End

TailDPLC_Walk37:	dplcHeader
	dplcEntry	8, $158
	dplcEntry	8, $188
	dplcEntry	8, $1A8
TailDPLC_Walk37_End

TailDPLC_Walk38:	dplcHeader
	dplcEntry	8, $168
	dplcEntry	8, $190
	dplcEntry	8, $4A4
TailDPLC_Walk38_End

TailDPLC_Walk41:	dplcHeader
	dplcEntry	2, $1B0
	dplcEntry	$10, $1B2
TailDPLC_Walk41_End

TailDPLC_Walk42:	dplcHeader
	dplcEntry	4, $1C2
	dplcEntry	2, $1C6
	dplcEntry	$10, $1C8
TailDPLC_Walk42_End

TailDPLC_Walk43:	dplcHeader
	dplcEntry	2, $1D8
	dplcEntry	$10, $1DA
TailDPLC_Walk43_End

TailDPLC_Walk44:	dplcHeader
	dplcEntry	2, $1EA
	dplcEntry	2, $1EC
	dplcEntry	$10, $1EE
TailDPLC_Walk44_End

TailDPLC_Walk45:	dplcHeader
	dplcEntry	2, $1B0
	dplcEntry	$10, $1FE
TailDPLC_Walk45_End

TailDPLC_Walk46:	dplcHeader
	dplcEntry	2, $20E
	dplcEntry	2, $1C6
	dplcEntry	$10, $210
TailDPLC_Walk46_End

TailDPLC_Walk47:	dplcHeader
	dplcEntry	2, $1D8
	dplcEntry	$10, $220
TailDPLC_Walk47_End

TailDPLC_Walk48:	dplcHeader
	dplcEntry	2, $230
	dplcEntry	2, $1EA
	dplcEntry	$10, $232
TailDPLC_Walk48_End

TailDPLC_Run11:	dplcHeader
	dplcEntry	$10, $242
	dplcEntry	8, $262
TailDPLC_Run11_End

TailDPLC_Run12:	dplcHeader
	dplcEntry	$10, $252
	dplcEntry	4, $26A
TailDPLC_Run12_End

TailDPLC_Run13:	dplcHeader
	dplcEntry	$10, $242
	dplcEntry	4, $26E
TailDPLC_Run13_End

TailDPLC_Run14:	dplcHeader
	dplcEntry	$10, $252
	dplcEntry	4, $26A
TailDPLC_Run14_End

TailDPLC_Run15:	dplcHeader
	dplcEntry	$10, $242
	dplcEntry	8, $272
TailDPLC_Run15_End

TailDPLC_Run16:	dplcHeader
	dplcEntry	$10, $252
	dplcEntry	8, $272
TailDPLC_Run16_End

TailDPLC_Run21:	dplcHeader
	dplcEntry	2, $27A
	dplcEntry	$C, $27C
	dplcEntry	$C, $298
TailDPLC_Run21_End

TailDPLC_Run22:	dplcHeader
	dplcEntry	4, $288
	dplcEntry	$C, $28C
	dplcEntry	4, $2A4
TailDPLC_Run22_End

TailDPLC_Run23:	dplcHeader
	dplcEntry	2, $27A
	dplcEntry	$C, $27C
	dplcEntry	4, $2A8
TailDPLC_Run23_End

TailDPLC_Run24:	dplcHeader
	dplcEntry	4, $288
	dplcEntry	$C, $28C
	dplcEntry	4, $2AC
TailDPLC_Run24_End

TailDPLC_Run25:	dplcHeader
	dplcEntry	2, $27A
	dplcEntry	$C, $27C
	dplcEntry	$C, $2B0
TailDPLC_Run25_End

TailDPLC_Run26:	dplcHeader
	dplcEntry	4, $288
	dplcEntry	$C, $28C
	dplcEntry	$C, $2B0
TailDPLC_Run26_End

TailDPLC_Run31:	dplcHeader
	dplcEntry	6, $2BC
	dplcEntry	8, $2C2
	dplcEntry	8, $2D8
TailDPLC_Run31_End

TailDPLC_Run32:	dplcHeader
	dplcEntry	6, $2CA
	dplcEntry	8, $2D0
	dplcEntry	4, $2E4
TailDPLC_Run32_End

TailDPLC_Run33:	dplcHeader
	dplcEntry	6, $2BC
	dplcEntry	8, $2C2
	dplcEntry	4, $2E0
TailDPLC_Run33_End

TailDPLC_Run34:	dplcHeader
	dplcEntry	6, $2CA
	dplcEntry	8, $2D0
	dplcEntry	4, $2E4
TailDPLC_Run34_End

TailDPLC_Run35:	dplcHeader
	dplcEntry	6, $2BC
	dplcEntry	8, $2C2
	dplcEntry	8, $2E8
TailDPLC_Run35_End

TailDPLC_Run36:	dplcHeader
	dplcEntry	6, $2CA
	dplcEntry	8, $2D0
	dplcEntry	8, $2E8
TailDPLC_Run36_End

TailDPLC_Run41:	dplcHeader
	dplcEntry	$C, $2F0
	dplcEntry	4, $2FC
	dplcEntry	$C, $298
TailDPLC_Run41_End

TailDPLC_Run42:	dplcHeader
	dplcEntry	$C, $300
	dplcEntry	4, $30C
	dplcEntry	4, $2A4
TailDPLC_Run42_End

TailDPLC_Run43:	dplcHeader
	dplcEntry	$C, $2F0
	dplcEntry	4, $2FC
	dplcEntry	4, $2A8
TailDPLC_Run43_End

TailDPLC_Run44:	dplcHeader
	dplcEntry	$C, $300
	dplcEntry	4, $30C
	dplcEntry	4, $2AC
TailDPLC_Run44_End

TailDPLC_Run45:	dplcHeader
	dplcEntry	$C, $2F0
	dplcEntry	4, $2FC
	dplcEntry	$C, $2B0
TailDPLC_Run45_End

TailDPLC_Run46:	dplcHeader
	dplcEntry	$C, $300
	dplcEntry	4, $30C
	dplcEntry	$C, $2B0
TailDPLC_Run46_End

TailDPLC_Roll1:	dplcHeader
	dplcEntry	$10, $310
TailDPLC_Roll1_End

TailDPLC_Roll2:	dplcHeader
	dplcEntry	$10, $320
TailDPLC_Roll2_End

TailDPLC_Roll3:	dplcHeader
	dplcEntry	$10, $330
TailDPLC_Roll3_End

TailDPLC_Spring1:	dplcHeader
	dplcEntry	4, $340
	dplcEntry	$C, $344
TailDPLC_Spring1_End

TailDPLC_Spring2:	dplcHeader
	dplcEntry	4, $340
	dplcEntry	$C, $350
TailDPLC_Spring2_End

TailDPLC_Duck:	dplcHeader
	dplcEntry	$C, $35C
TailDPLC_Duck_End

TailDPLC_Hurt:	dplcHeader
	dplcEntry	$10, $368
TailDPLC_Hurt_End

TailDPLC_Death:	dplcHeader
	dplcEntry	$10, $378
TailDPLC_Death_End

TailDPLC_Fly1:	dplcHeader
	dplcEntry	$10, $388
	dplcEntry	8, $398
TailDPLC_Fly1_End

TailDPLC_Fly2:	dplcHeader
	dplcEntry	$10, $388
	dplcEntry	8, $398
TailDPLC_Fly2_End

TailDPLC_Spindash1:	dplcHeader
	dplcEntry	$10, $3A0
TailDPLC_Spindash1_End

TailDPLC_Spindash2:	dplcHeader
	dplcEntry	$10, $3B0
TailDPLC_Spindash2_End

TailDPLC_Spindash3:	dplcHeader
	dplcEntry	$10, $3C0
TailDPLC_Spindash3_End

TailDPLC_Push1:	dplcHeader
	dplcEntry	6, $3D0
	dplcEntry	8, $3D6
TailDPLC_Push1_End

TailDPLC_Push2:	dplcHeader
	dplcEntry	6, $3D0
	dplcEntry	6, $3DE
TailDPLC_Push2_End

TailDPLC_Push3:	dplcHeader
	dplcEntry	6, $3D0
	dplcEntry	6, $3E4
TailDPLC_Push3_End

TailDPLC_Push4:	dplcHeader
	dplcEntry	6, $3D0
	dplcEntry	6, $3EA
TailDPLC_Push4_End

TailDPLC_Stop1:	dplcHeader
	dplcEntry	6, $3F0
	dplcEntry	8, $3F6
TailDPLC_Stop1_End

TailDPLC_Stop2:	dplcHeader
	dplcEntry	6, $3FE
	dplcEntry	8, $404
TailDPLC_Stop2_End

TailDPLC_Balance1:	dplcHeader
	dplcEntry	2, $40C
	dplcEntry	$C, $40E
TailDPLC_Balance1_End

TailDPLC_Balance2:	dplcHeader
	dplcEntry	6, $41A
	dplcEntry	8, $420
TailDPLC_Balance2_End

TailDPLC_WaterSlide:	dplcHeader
	dplcEntry	$10, $428
TailDPLC_WaterSlide_End

TailDPLC_Hang1:	dplcHeader
	dplcEntry	$10, $438
	dplcEntry	4, $448
TailDPLC_Hang1_End

TailDPLC_Hang2:	dplcHeader
	dplcEntry	$10, $44C
	dplcEntry	4, $45C
TailDPLC_Hang2_End

TailDPLC_Float1:	dplcHeader
	dplcEntry	4, $460
	dplcEntry	$C, $464
TailDPLC_Float1_End

TailDPLC_Float2:	dplcHeader
	dplcEntry	8, $470
	dplcEntry	8, $470
TailDPLC_Float2_End

TailDPLC_Float3:	dplcHeader
	dplcEntry	4, $460
	dplcEntry	$C, $464
TailDPLC_Float3_End

TailDPLC_Float4:	dplcHeader
	dplcEntry	8, $478
	dplcEntry	4, $480
TailDPLC_Float4_End

TailDPLC_Float5:	dplcHeader
	dplcEntry	8, $478
	dplcEntry	4, $480
TailDPLC_Float5_End

TailDPLC_Float6:	dplcHeader
	dplcEntry	4, $484
	dplcEntry	$C, $488
TailDPLC_Float6_End

TailDPLC_GetAir:	dplcHeader
	dplcEntry	$10, $494
TailDPLC_GetAir_End

TailDPLC_FlyTired1:	dplcHeader
	dplcEntry	$10, $4AC
	dplcEntry	1, $4BC
TailDPLC_FlyTired1_End

TailDPLC_FlyTired2:	dplcHeader
	dplcEntry	$10, $4BD
	dplcEntry	1, $545
TailDPLC_FlyTired2_End

TailDPLC_Swim1:	dplcHeader
	dplcEntry	$10, $5E7
	dplcEntry	4, $688
TailDPLC_Swim1_End

TailDPLC_Swim2:	dplcHeader
	dplcEntry	$10, $4CD
TailDPLC_Swim2_End

TailDPLC_Swim3:	dplcHeader
	dplcEntry	$10, $4DD
TailDPLC_Swim3_End

TailDPLC_Swim4:	dplcHeader
	dplcEntry	$10, $4ED
	dplcEntry	4, $4FD
TailDPLC_Swim4_End

TailDPLC_Swim5:	dplcHeader
	dplcEntry	$10, $501
TailDPLC_Swim5_End

TailDPLC_SwimTired1:	dplcHeader
	dplcEntry	$10, $511
	dplcEntry	4, $521
TailDPLC_SwimTired1_End

TailDPLC_SwimTired2:	dplcHeader
	dplcEntry	$10, $525
	dplcEntry	4, $546
TailDPLC_SwimTired2_End

TailDPLC_SwimTired3:	dplcHeader
	dplcEntry	$10, $535
TailDPLC_SwimTired3_End
	even
