; ---------------------------------------------------------------------------
; Sonic 1 Sprite Mappings - Generated by Sonic Triad Studio
; To be used with spritePiece Macro. Set SonicMappingsVer to 1 to use this mapping script.
; ---------------------------------------------------------------------------
Map_Tails:	mappingsTable
ptr_TailMap_Null:		mappingsTableEntry.w	TailMap_Null
ptr_TailMap_Stand1:		mappingsTableEntry.w	TailMap_Stand
ptr_TailMap_Stand2:		mappingsTableEntry.w	TailMap_Stand
ptr_TailMap_Stand3:		mappingsTableEntry.w	TailMap_Stand
ptr_TailMap_LookUp:		mappingsTableEntry.w	TailMap_Stand
ptr_TailMap_Idle1:		mappingsTableEntry.w	TailMap_Idle1
ptr_TailMap_Idle2:		mappingsTableEntry.w	TailMap_Idle1
ptr_TailMap_Idle3:		mappingsTableEntry.w	TailMap_Idle2
ptr_TailMap_Idle4:		mappingsTableEntry.w	TailMap_Idle2
ptr_TailMap_Walk11:		mappingsTableEntry.w	TailMap_Walk11
ptr_TailMap_Walk12:		mappingsTableEntry.w	TailMap_Walk12
ptr_TailMap_Walk13:		mappingsTableEntry.w	TailMap_Walk13
ptr_TailMap_Walk14:		mappingsTableEntry.w	TailMap_Walk14
ptr_TailMap_Walk15:		mappingsTableEntry.w	TailMap_Walk11
ptr_TailMap_Walk16:		mappingsTableEntry.w	TailMap_Walk12
ptr_TailMap_Walk17:		mappingsTableEntry.w	TailMap_Walk15
ptr_TailMap_Walk18:		mappingsTableEntry.w	TailMap_Walk14
ptr_TailMap_Walk21:		mappingsTableEntry.w	TailMap_Walk21
ptr_TailMap_Walk22:		mappingsTableEntry.w	TailMap_Walk22
ptr_TailMap_Walk23:		mappingsTableEntry.w	TailMap_Walk23
ptr_TailMap_Walk24:		mappingsTableEntry.w	TailMap_Walk24
ptr_TailMap_Walk25:		mappingsTableEntry.w	TailMap_Walk21
ptr_TailMap_Walk26:		mappingsTableEntry.w	TailMap_Walk25
ptr_TailMap_Walk27:		mappingsTableEntry.w	TailMap_Walk23
ptr_TailMap_Walk28:		mappingsTableEntry.w	TailMap_Walk26
ptr_TailMap_Walk31:		mappingsTableEntry.w	TailMap_Walk31
ptr_TailMap_Walk32:		mappingsTableEntry.w	TailMap_Walk32
ptr_TailMap_Walk33:		mappingsTableEntry.w	TailMap_Walk33
ptr_TailMap_Walk34:		mappingsTableEntry.w	TailMap_Walk34
ptr_TailMap_Walk35:		mappingsTableEntry.w	TailMap_Walk31
ptr_TailMap_Walk36:		mappingsTableEntry.w	TailMap_Walk32
ptr_TailMap_Walk37:		mappingsTableEntry.w	TailMap_Walk33
ptr_TailMap_Walk38:		mappingsTableEntry.w	TailMap_Walk34
ptr_TailMap_Walk41:		mappingsTableEntry.w	TailMap_Walk41
ptr_TailMap_Walk42:		mappingsTableEntry.w	TailMap_Walk42
ptr_TailMap_Walk43:		mappingsTableEntry.w	TailMap_Walk43
ptr_TailMap_Walk44:		mappingsTableEntry.w	TailMap_Walk44
ptr_TailMap_Walk45:		mappingsTableEntry.w	TailMap_Walk41
ptr_TailMap_Walk46:		mappingsTableEntry.w	TailMap_Walk45
ptr_TailMap_Walk47:		mappingsTableEntry.w	TailMap_Walk43
ptr_TailMap_Walk48:		mappingsTableEntry.w	TailMap_Walk46
ptr_TailMap_Run11:		mappingsTableEntry.w	TailMap_Run11
ptr_TailMap_Run12:		mappingsTableEntry.w	TailMap_Run12
ptr_TailMap_Run13:		mappingsTableEntry.w	TailMap_Run12
ptr_TailMap_Run14:		mappingsTableEntry.w	TailMap_Run13
ptr_TailMap_Run15:		mappingsTableEntry.w	TailMap_Run11
ptr_TailMap_Run16:		mappingsTableEntry.w	TailMap_Run14
ptr_TailMap_Run21:		mappingsTableEntry.w	TailMap_Run21
ptr_TailMap_Run22:		mappingsTableEntry.w	TailMap_Run22
ptr_TailMap_Run23:		mappingsTableEntry.w	TailMap_Run23
ptr_TailMap_Run24:		mappingsTableEntry.w	TailMap_Run22
ptr_TailMap_Run25:		mappingsTableEntry.w	TailMap_Run24
ptr_TailMap_Run26:		mappingsTableEntry.w	TailMap_Run25
ptr_TailMap_Run31:		mappingsTableEntry.w	TailMap_Run31
ptr_TailMap_Run32:		mappingsTableEntry.w	TailMap_Run32
ptr_TailMap_Run33:		mappingsTableEntry.w	TailMap_Run32
ptr_TailMap_Run34:		mappingsTableEntry.w	TailMap_Run32
ptr_TailMap_Run35:		mappingsTableEntry.w	TailMap_Run32
ptr_TailMap_Run36:		mappingsTableEntry.w	TailMap_Run33
ptr_TailMap_Run41:		mappingsTableEntry.w	TailMap_Run41
ptr_TailMap_Run42:		mappingsTableEntry.w	TailMap_Run42
ptr_TailMap_Run43:		mappingsTableEntry.w	TailMap_Run42
ptr_TailMap_Run44:		mappingsTableEntry.w	TailMap_Run42
ptr_TailMap_Run45:		mappingsTableEntry.w	TailMap_Run43
ptr_TailMap_Run46:		mappingsTableEntry.w	TailMap_Run44
ptr_TailMap_Roll1:		mappingsTableEntry.w	TailMap_Roll
ptr_TailMap_Roll2:		mappingsTableEntry.w	TailMap_Roll
ptr_TailMap_Roll3:		mappingsTableEntry.w	TailMap_Roll
ptr_TailMap_Spring1:	mappingsTableEntry.w	TailMap_Spring
ptr_TailMap_Spring2:	mappingsTableEntry.w	TailMap_Spring
ptr_TailMap_Duck:		mappingsTableEntry.w	TailMap_Duck
ptr_TailMap_Hurt:		mappingsTableEntry.w	TailMap_Hurt
ptr_TailMap_Death:		mappingsTableEntry.w	TailMap_Death
ptr_TailMap_Fly1:		mappingsTableEntry.w	TailMap_Fly
ptr_TailMap_Fly2:		mappingsTableEntry.w	TailMap_Fly
ptr_TailMap_Spindash1:	mappingsTableEntry.w	TailMap_Spindash
ptr_TailMap_Spindash2:	mappingsTableEntry.w	TailMap_Spindash
ptr_TailMap_Spindash3:	mappingsTableEntry.w	TailMap_Spindash
ptr_TailMap_Push1:		mappingsTableEntry.w	TailMap_Push1
ptr_TailMap_Push2:		mappingsTableEntry.w	TailMap_Push2
ptr_TailMap_Push3:		mappingsTableEntry.w	TailMap_Push2
ptr_TailMap_Push4:		mappingsTableEntry.w	TailMap_Push2
ptr_TailMap_Stop1:		mappingsTableEntry.w	TailMap_Stop
ptr_TailMap_Stop2:		mappingsTableEntry.w	TailMap_Stop
ptr_TailMap_Balance1:	mappingsTableEntry.w	TailMap_Balance1
ptr_TailMap_Balance2:	mappingsTableEntry.w	TailMap_Balance2
ptr_TailMap_WaterSlide:	mappingsTableEntry.w	TailMap_Hurt
ptr_TailMap_Hang1:		mappingsTableEntry.w	TailMap_Hang
ptr_TailMap_Hang2:		mappingsTableEntry.w	TailMap_Hang
ptr_TailMap_Float1:		mappingsTableEntry.w	TailMap_Float1
ptr_TailMap_Float2:		mappingsTableEntry.w	TailMap_Float2
ptr_TailMap_Float3:		mappingsTableEntry.w	TailMap_Float3
ptr_TailMap_Float4:		mappingsTableEntry.w	TailMap_Float4
ptr_TailMap_Float5:		mappingsTableEntry.w	TailMap_Float5
ptr_TailMap_Float6:		mappingsTableEntry.w	TailMap_Float1
ptr_TailMap_GetAir:		mappingsTableEntry.w	TailMap_GetAir
ptr_TailMap_FlyTired1:	mappingsTableEntry.w	TailMap_FlyTired
ptr_TailMap_FlyTired2:	mappingsTableEntry.w	TailMap_FlyTired
ptr_TailMap_Swim1:		mappingsTableEntry.w	TailMap_Swim1
ptr_TailMap_Swim2:		mappingsTableEntry.w	TailMap_Swim2
ptr_TailMap_Swim3:		mappingsTableEntry.w	TailMap_Swim3
ptr_TailMap_Swim4:		mappingsTableEntry.w	TailMap_Swim4
ptr_TailMap_Swim5:		mappingsTableEntry.w	TailMap_Swim2
ptr_TailMap_SwimTired1:	mappingsTableEntry.w	TailMap_SwimTired1
ptr_TailMap_SwimTired2:	mappingsTableEntry.w	TailMap_SwimTired2
ptr_TailMap_SwimTired3:	mappingsTableEntry.w	TailMap_SwimTired3

TailMap_Null:	spriteHeader
TailMap_Null_End

TailMap_Stand:	spriteHeader
	spritePiece	-$C, -$10, 3, 2, 0, 0, 0, 0, 0
	spritePiece	-$C, 0, 3, 2, 6, 0, 0, 0, 0
TailMap_Stand_End

TailMap_Idle1:	spriteHeader
	spritePiece	-$C, -$10, 3, 4, 0, 0, 0, 0, 0
TailMap_Idle1_End

TailMap_Idle2:	spriteHeader
	spritePiece	-$C, -$10, 3, 2, 0, 0, 0, 0, 0
	spritePiece	-$C, 0, 3, 2, 6, 0, 0, 0, 0
TailMap_Idle2_End

TailMap_Walk11:	spriteHeader
	spritePiece	-$10, -$14, 3, 2, 0, 0, 0, 0, 0
	spritePiece	-$10, -4, 4, 2, 6, 0, 0, 0, 0
	spritePiece	-$1E, -4, 3, 2, $E, 0, 0, 0, 0
TailMap_Walk11_End

TailMap_Walk12:	spriteHeader
	spritePiece	-$D, -$10, 3, 2, 0, 0, 0, 0, 0
	spritePiece	-$10, 0, 4, 2, 6, 0, 0, 0, 0
	spritePiece	-$1C, 0, 3, 2, $E, 0, 0, 0, 0
TailMap_Walk12_End

TailMap_Walk13:	spriteHeader
	spritePiece	-8, -$10, 3, 2, 0, 0, 0, 0, 0
	spritePiece	-$D, 0, 3, 2, 6, 0, 0, 0, 0
	spritePiece	-$1C, -3, 3, 2, $C, 0, 0, 0, 0
TailMap_Walk13_End

TailMap_Walk14:	spriteHeader
	spritePiece	-$E, -$10, 3, 2, 0, 0, 0, 0, 0
	spritePiece	-$E, 0, 3, 2, 6, 0, 0, 0, 0
	spritePiece	-$1A, -3, 3, 2, $C, 0, 0, 0, 0
TailMap_Walk14_End

TailMap_Walk15:	spriteHeader
	spritePiece	-8, -$10, 3, 2, 0, 0, 0, 0, 0
	spritePiece	-$F, 0, 3, 2, 6, 0, 0, 0, 0
	spritePiece	-$1C, -3, 3, 2, $C, 0, 0, 0, 0
TailMap_Walk15_End

TailMap_Walk21:	spriteHeader
	spritePiece	-$D, -$1D, 1, 2, 0, 0, 0, 0, 0
	spritePiece	-$14, -$D, 1, 4, 2, 0, 0, 0, 0
	spritePiece	-$C, -$D, 3, 4, 6, 0, 0, 0, 0
TailMap_Walk21_End

TailMap_Walk22:	spriteHeader
	spritePiece	-$A, -$19, 2, 2, 0, 0, 0, 0, 0
	spritePiece	-$12, -9, 3, 4, 4, 0, 0, 0, 0
	spritePiece	6, -2, 2, 2, $10, 0, 0, 0, 0
TailMap_Walk22_End

TailMap_Walk23:	spriteHeader
	spritePiece	-8, -$1A, 2, 2, 0, 0, 0, 0, 0
	spritePiece	-$11, -$A, 1, 4, 4, 0, 0, 0, 0
	spritePiece	-9, -$A, 3, 4, 8, 0, 0, 0, 0
TailMap_Walk23_End

TailMap_Walk24:	spriteHeader
	spritePiece	-9, -$1D, 1, 2, 0, 0, 0, 0, 0
	spritePiece	-$14, -$D, 4, 4, 2, 0, 0, 0, 0
	spritePiece	$C, -5, 1, 2, $12, 0, 0, 0, 0
TailMap_Walk24_End

TailMap_Walk25:	spriteHeader
	spritePiece	-$A, -$19, 2, 2, 0, 0, 0, 0, 0
	spritePiece	-$12, -9, 3, 4, 4, 0, 0, 0, 0
	spritePiece	6, -1, 2, 2, $10, 0, 0, 0, 0
TailMap_Walk25_End

TailMap_Walk26:	spriteHeader
	spritePiece	-9, -$1D, 1, 2, 0, 0, 0, 0, 0
	spritePiece	-$14, -$D, 4, 4, 2, 0, 0, 0, 0
	spritePiece	$C, 3, 1, 2, $12, 0, 0, 0, 0
TailMap_Walk26_End

TailMap_Walk31:	spriteHeader
	spritePiece	-$14, -$10, 2, 4, 0, 0, 0, 0, 0
	spritePiece	-4, -$10, 2, 4, 8, 0, 0, 0, 0
	spritePiece	-4, 6, 2, 4, $10, 0, 0, 0, 0
TailMap_Walk31_End

TailMap_Walk32:	spriteHeader
	spritePiece	-$10, -$10, 2, 4, 0, 0, 0, 0, 0
	spritePiece	0, -$10, 2, 4, 8, 0, 0, 0, 0
	spritePiece	0, 4, 2, 4, $10, 0, 0, 0, 0
TailMap_Walk32_End

TailMap_Walk33:	spriteHeader
	spritePiece	-$10, -$10, 2, 4, 0, 0, 0, 0, 0
	spritePiece	0, -$10, 2, 4, 8, 0, 0, 0, 0
	spritePiece	-3, 4, 2, 4, $10, 0, 0, 0, 0
TailMap_Walk33_End

TailMap_Walk34:	spriteHeader
	spritePiece	-$10, -$10, 2, 4, 0, 0, 0, 0, 0
	spritePiece	0, -$10, 2, 4, 8, 0, 0, 0, 0
	spritePiece	-3, 4, 2, 4, $10, 0, 0, 0, 0
TailMap_Walk34_End

TailMap_Walk41:	spriteHeader
	spritePiece	-$15, 4, 1, 2, 0, 0, 0, 0, 0
	spritePiece	-$D, -$C, 4, 4, 2, 0, 0, 0, 0
TailMap_Walk41_End

TailMap_Walk42:	spriteHeader
	spritePiece	-8, -$1E, 2, 2, 0, 0, 0, 0, 0
	spritePiece	-$10, -6, 1, 2, 4, 0, 0, 0, 0
	spritePiece	-8, -$E, 4, 4, 6, 0, 0, 0, 0
TailMap_Walk42_End

TailMap_Walk43:	spriteHeader
	spritePiece	-$14, -7, 1, 2, 0, 0, 0, 0, 0
	spritePiece	-$C, -$F, 4, 4, 2, 0, 0, 0, 0
TailMap_Walk43_End

TailMap_Walk44:	spriteHeader
	spritePiece	-$11, -4, 1, 2, 0, 0, 0, 0, 0
	spritePiece	-1, -$1B, 1, 2, 2, 0, 0, 0, 0
	spritePiece	-9, -$B, 4, 4, 4, 0, 0, 0, 0
TailMap_Walk44_End

TailMap_Walk45:	spriteHeader
	spritePiece	0, -$1E, 1, 2, 0, 0, 0, 0, 0
	spritePiece	-$10, -6, 1, 2, 2, 0, 0, 0, 0
	spritePiece	-8, -$E, 4, 4, 4, 0, 0, 0, 0
TailMap_Walk45_End

TailMap_Walk46:	spriteHeader
	spritePiece	-1, -$1C, 1, 2, 0, 0, 0, 0, 0
	spritePiece	-$11, -4, 1, 2, 2, 0, 0, 0, 0
	spritePiece	-9, -$C, 4, 4, 4, 0, 0, 0, 0
TailMap_Walk46_End

TailMap_Run11:	spriteHeader
	spritePiece	-$10, -$10, 4, 4, 0, 0, 0, 0, 0
	spritePiece	-$16, -$10, 2, 4, $10, 0, 0, 0, 0
TailMap_Run11_End

TailMap_Run12:	spriteHeader
	spritePiece	-$10, -$10, 4, 4, 0, 0, 0, 0, 0
	spritePiece	-$16, -8, 2, 2, $10, 0, 0, 0, 0
TailMap_Run12_End

TailMap_Run13:	spriteHeader
	spritePiece	-$10, -$10, 4, 4, 0, 0, 0, 0, 0
	spritePiece	-$16, -8, 2, 2, $10, 0, 1, 0, 0
TailMap_Run13_End

TailMap_Run14:	spriteHeader
	spritePiece	-$10, -$10, 4, 4, 0, 0, 0, 0, 0
	spritePiece	-$18, -$10, 2, 4, $10, 1, 1, 0, 0
TailMap_Run14_End

TailMap_Run21:	spriteHeader
	spritePiece	-6, -$1C, 1, 2, 0, 0, 0, 0, 0
	spritePiece	-$10, -$C, 3, 4, 2, 0, 0, 0, 0
	spritePiece	-$18, -2, 3, 4, $E, 0, 0, 0, 0
TailMap_Run21_End

TailMap_Run22:	spriteHeader
	spritePiece	-8, -$1C, 2, 2, 0, 0, 0, 0, 0
	spritePiece	-$10, -$C, 3, 4, 4, 0, 0, 0, 0
	spritePiece	-$11, 4, 2, 2, $10, 0, 0, 0, 0
TailMap_Run22_End

TailMap_Run23:	spriteHeader
	spritePiece	-6, -$1C, 1, 2, 0, 0, 0, 0, 0
	spritePiece	-$10, -$C, 3, 4, 2, 0, 0, 0, 0
	spritePiece	-$11, 4, 2, 2, $E, 0, 0, 0, 0
TailMap_Run23_End

TailMap_Run24:	spriteHeader
	spritePiece	-6, -$1C, 1, 2, 0, 0, 0, 0, 0
	spritePiece	-$10, -$C, 3, 4, 2, 0, 0, 0, 0
	spritePiece	-$16, -4, 3, 4, $E, 0, 0, 0, 0
TailMap_Run24_End

TailMap_Run25:	spriteHeader
	spritePiece	-8, -$1C, 2, 2, 0, 0, 0, 0, 0
	spritePiece	-$10, -$C, 3, 4, 4, 0, 0, 0, 0
	spritePiece	-$16, -9, 3, 4, $10, 1, 1, 0, 0
TailMap_Run25_End

TailMap_Run31:	spriteHeader
	spritePiece	-$10, -$10, 3, 2, 0, 0, 0, 0, 0
	spritePiece	-$10, 0, 4, 2, 6, 0, 0, 0, 0
	spritePiece	-$10, 6, 4, 2, $E, 0, 0, 0, 0
TailMap_Run31_End

TailMap_Run32:	spriteHeader
	spritePiece	-$10, -$10, 3, 2, 0, 0, 0, 0, 0
	spritePiece	-$10, 0, 4, 2, 6, 0, 0, 0, 0
	spritePiece	-8, 6, 2, 2, $E, 0, 0, 0, 0
TailMap_Run32_End

TailMap_Run33:	spriteHeader
	spritePiece	-$10, -$10, 3, 2, 0, 0, 0, 0, 0
	spritePiece	-$10, 0, 4, 2, 6, 0, 0, 0, 0
	spritePiece	-$10, 8, 4, 2, $E, 1, 1, 0, 0
TailMap_Run33_End

TailMap_Run41:	spriteHeader
	spritePiece	-$14, -8, 3, 4, 0, 0, 0, 0, 0
	spritePiece	4, -8, 2, 2, $C, 0, 0, 0, 0
	spritePiece	0, -2, 3, 4, $10, 1, 0, 0, 0
TailMap_Run41_End

TailMap_Run42:	spriteHeader
	spritePiece	-$14, -8, 3, 4, 0, 0, 0, 0, 0
	spritePiece	4, -8, 2, 2, $C, 0, 0, 0, 0
	spritePiece	4, 1, 2, 2, $10, 1, 0, 0, 0
TailMap_Run42_End

TailMap_Run43:	spriteHeader
	spritePiece	-$14, -8, 3, 4, 0, 0, 0, 0, 0
	spritePiece	4, -8, 2, 2, $C, 0, 0, 0, 0
	spritePiece	-2, -4, 3, 4, $10, 1, 0, 0, 0
TailMap_Run43_End

TailMap_Run44:	spriteHeader
	spritePiece	-$14, -8, 3, 4, 0, 0, 0, 0, 0
	spritePiece	4, -8, 2, 2, $C, 0, 0, 0, 0
	spritePiece	-1, -9, 3, 4, $10, 0, 1, 0, 0
TailMap_Run44_End

TailMap_Roll:	spriteHeader
	spritePiece	-$10, -$10, 4, 4, 0, 0, 0, 0, 0
TailMap_Roll_End

TailMap_Spring:	spriteHeader
	spritePiece	-8, -$18, 2, 2, 0, 0, 0, 0, 0
	spritePiece	-$10, -8, 3, 4, 4, 0, 0, 0, 0
TailMap_Spring_End

TailMap_Duck:	spriteHeader
	spritePiece	-7, -$10, 3, 4, 0, 0, 0, 0, 0
TailMap_Duck_End

TailMap_Hurt:	spriteHeader
	spritePiece	-$10, -$10, 4, 4, 0, 0, 0, 0, 0
TailMap_Hurt_End

TailMap_Death:	spriteHeader
	spritePiece	-$10, -$10, 4, 4, 0, 0, 0, 0, 0
TailMap_Death_End

TailMap_Fly:	spriteHeader
	spritePiece	-$10, -$10, 4, 4, 0, 0, 0, 0, 0
	spritePiece	-$16, -$1C, 4, 2, $10, 0, 0, 0, 0
TailMap_Fly_End

TailMap_Spindash:	spriteHeader
	spritePiece	-$10, -$C, 4, 4, 0, 0, 0, 0, 0
TailMap_Spindash_End

TailMap_Push1:	spriteHeader
	spritePiece	-8, -$10, 3, 2, 0, 0, 0, 0, 0
	spritePiece	-$10, 0, 4, 2, 6, 0, 0, 0, 0
TailMap_Push1_End

TailMap_Push2:	spriteHeader
	spritePiece	-8, -$10, 3, 2, 0, 0, 0, 0, 0
	spritePiece	-8, 0, 3, 2, 6, 0, 0, 0, 0
TailMap_Push2_End

TailMap_Stop:	spriteHeader
	spritePiece	-$10, -$10, 3, 2, 0, 0, 0, 0, 0
	spritePiece	-$10, 0, 4, 2, 6, 0, 0, 0, 0
TailMap_Stop_End

TailMap_Balance1:	spriteHeader
	spritePiece	-$18, -8, 1, 2, 0, 0, 0, 0, 0
	spritePiece	-$10, -$10, 3, 4, 2, 0, 0, 0, 0
TailMap_Balance1_End

TailMap_Balance2:	spriteHeader
	spritePiece	-$10, -$10, 3, 2, 0, 0, 0, 0, 0
	spritePiece	-$18, 0, 4, 2, 6, 0, 0, 0, 0
TailMap_Balance2_End

TailMap_Hang:	spriteHeader
	spritePiece	-$14, -$10, 4, 4, 0, 0, 0, 0, 0
	spritePiece	$C, -$10, 1, 4, $10, 0, 0, 0, 0
TailMap_Hang_End

TailMap_Float1:	spriteHeader
	spritePiece	-$14, -8, 2, 2, 0, 0, 0, 0, 0
	spritePiece	-4, -$10, 3, 4, 4, 0, 0, 0, 0
TailMap_Float1_End

TailMap_Float2:	spriteHeader
	spritePiece	-$10, -$10, 2, 4, 0, 0, 0, 0, 0
	spritePiece	0, -$10, 2, 4, 8, 1, 0, 0, 0
TailMap_Float2_End

TailMap_Float3:	spriteHeader
	spritePiece	4, -8, 2, 2, 0, 1, 0, 0, 0
	spritePiece	-$14, -$10, 3, 4, 4, 1, 0, 0, 0
TailMap_Float3_End

TailMap_Float4:	spriteHeader
	spritePiece	-$10, -$10, 2, 4, 0, 0, 0, 0, 0
	spritePiece	0, -8, 2, 2, 8, 0, 0, 0, 0
TailMap_Float4_End

TailMap_Float5:	spriteHeader
	spritePiece	0, -$10, 2, 4, 0, 1, 0, 0, 0
	spritePiece	-$10, -8, 2, 2, 8, 1, 0, 0, 0
TailMap_Float5_End

TailMap_GetAir:	spriteHeader
	spritePiece	-$10, -$10, 4, 4, 0, 0, 0, 0, 0
TailMap_GetAir_End

TailMap_FlyTired:	spriteHeader
	spritePiece	-$F, -$13, 4, 4, 0, 0, 0, 0, 0
	spritePiece	-$13, -$13, 1, 1, $10, 0, 0, 0, 0
TailMap_FlyTired_End

TailMap_Swim1:	spriteHeader
	spritePiece	-$E, -$13, 4, 4, 0, 0, 0, 0, 0
	spritePiece	$11, -$13, 1, 4, $10, 0, 0, 0, 0
TailMap_Swim1_End

TailMap_Swim2:	spriteHeader
	spritePiece	-$D, -$13, 4, 4, 0, 0, 0, 0, 0
TailMap_Swim2_End

TailMap_Swim3:	spriteHeader
	spritePiece	-$C, -$13, 4, 4, 0, 0, 0, 0, 0
TailMap_Swim3_End

TailMap_Swim4:	spriteHeader
	spritePiece	-5, -$13, 4, 4, 0, 0, 0, 0, 0
	spritePiece	-$D, -$13, 1, 4, $10, 0, 0, 0, 0
TailMap_Swim4_End

TailMap_SwimTired1:	spriteHeader
	spritePiece	-$11, -$13, 4, 4, 0, 0, 0, 0, 0
	spritePiece	$F, -$13, 1, 4, $10, 0, 0, 0, 0
TailMap_SwimTired1_End

TailMap_SwimTired2:	spriteHeader
	spritePiece	-$D, -$17, 4, 4, 0, 0, 0, 0, 0
	spritePiece	$F, -$17, 1, 4, $10, 0, 0, 0, 0
TailMap_SwimTired2_End

TailMap_SwimTired3:	spriteHeader
	spritePiece	-$D, -$16, 4, 4, 0, 0, 0, 0, 0
TailMap_SwimTired3_End

		even

fr_TailNull:	equ	(ptr_TailMap_Null-Map_Tails)/2		; 0
fr_TailStand1:	equ	(ptr_TailMap_Stand1-Map_Tails)/2	; 1
fr_TailStand2:	equ	(ptr_TailMap_Stand2-Map_Tails)/2	; 2
fr_TailStand3:	equ	(ptr_TailMap_Stand3-Map_Tails)/2	; 3
fr_TailLookUp:	equ	(ptr_TailMap_LookUp-Map_Tails)/2	; 4
fr_TailIdle1:	equ	(ptr_TailMap_Idle1-Map_Tails)/2		; 5
fr_TailIdle2:	equ	(ptr_TailMap_Idle2-Map_Tails)/2		; 6
fr_TailIdle3:	equ	(ptr_TailMap_Idle3-Map_Tails)/2		; 7
fr_TailIdle4:	equ	(ptr_TailMap_Idle4-Map_Tails)/2		; 8
fr_TailWalk11:	equ	(ptr_TailMap_Walk11-Map_Tails)/2	; E
fr_TailWalk12:	equ	(ptr_TailMap_Walk12-Map_Tails)/2	; F
fr_TailWalk13:	equ	(ptr_TailMap_Walk13-Map_Tails)/2	; 10
fr_TailWalk14:	equ	(ptr_TailMap_Walk14-Map_Tails)/2	; 11
fr_TailWalk15:	equ	(ptr_TailMap_Walk15-Map_Tails)/2	; 12
fr_TailWalk16:	equ	(ptr_TailMap_Walk16-Map_Tails)/2	; 13
fr_TailWalk17:	equ	(ptr_TailMap_Walk17-Map_Tails)/2	; 14
fr_TailWalk18:	equ	(ptr_TailMap_Walk18-Map_Tails)/2	; 15
fr_TailWalk21:	equ	(ptr_TailMap_Walk21-Map_Tails)/2	; 16
fr_TailWalk22:	equ	(ptr_TailMap_Walk22-Map_Tails)/2	; 17
fr_TailWalk23:	equ	(ptr_TailMap_Walk23-Map_Tails)/2	; 18
fr_TailWalk24:	equ	(ptr_TailMap_Walk24-Map_Tails)/2	; 19
fr_TailWalk25:	equ	(ptr_TailMap_Walk25-Map_Tails)/2	; 1A
fr_TailWalk26:	equ	(ptr_TailMap_Walk26-Map_Tails)/2	; 1B
fr_TailWalk27:	equ	(ptr_TailMap_Walk27-Map_Tails)/2	; 1C
fr_TailWalk28:	equ	(ptr_TailMap_Walk28-Map_Tails)/2	; 1D
fr_TailWalk31:	equ	(ptr_TailMap_Walk31-Map_Tails)/2	; 1E
fr_TailWalk32:	equ	(ptr_TailMap_Walk32-Map_Tails)/2	; 1F
fr_TailWalk33:	equ	(ptr_TailMap_Walk33-Map_Tails)/2	; 20
fr_TailWalk34:	equ	(ptr_TailMap_Walk34-Map_Tails)/2	; 21
fr_TailWalk35:	equ	(ptr_TailMap_Walk35-Map_Tails)/2	; 22
fr_TailWalk36:	equ	(ptr_TailMap_Walk36-Map_Tails)/2	; 23
fr_TailWalk37:	equ	(ptr_TailMap_Walk37-Map_Tails)/2	; 24
fr_TailWalk38:	equ	(ptr_TailMap_Walk38-Map_Tails)/2	; 25
fr_TailWalk41:	equ	(ptr_TailMap_Walk41-Map_Tails)/2	; 26
fr_TailWalk42:	equ	(ptr_TailMap_Walk42-Map_Tails)/2	; 27
fr_TailWalk43:	equ	(ptr_TailMap_Walk43-Map_Tails)/2	; 28
fr_TailWalk44:	equ	(ptr_TailMap_Walk44-Map_Tails)/2	; 29
fr_TailWalk45:	equ	(ptr_TailMap_Walk45-Map_Tails)/2	; 2A
fr_TailWalk46:	equ	(ptr_TailMap_Walk46-Map_Tails)/2	; 2B
fr_TailWalk47:	equ	(ptr_TailMap_Walk47-Map_Tails)/2	; 2C
fr_TailWalk48:	equ	(ptr_TailMap_Walk48-Map_Tails)/2	; 2D
fr_TailRun11:	equ	(ptr_TailMap_Run11-Map_Tails)/2	; 2E
fr_TailRun12:	equ	(ptr_TailMap_Run12-Map_Tails)/2	; 2F
fr_TailRun13:	equ	(ptr_TailMap_Run13-Map_Tails)/2	; 30
fr_TailRun14:	equ	(ptr_TailMap_Run14-Map_Tails)/2	; 31
fr_TailRun15:	equ	(ptr_TailMap_Run15-Map_Tails)/2	; 32
fr_TailRun16:	equ	(ptr_TailMap_Run16-Map_Tails)/2	; 33
fr_TailRun21:	equ	(ptr_TailMap_Run21-Map_Tails)/2	; 34
fr_TailRun22:	equ	(ptr_TailMap_Run22-Map_Tails)/2	; 35
fr_TailRun23:	equ	(ptr_TailMap_Run23-Map_Tails)/2	; 36
fr_TailRun24:	equ	(ptr_TailMap_Run24-Map_Tails)/2	; 37
fr_TailRun25:	equ	(ptr_TailMap_Run25-Map_Tails)/2	; 38
fr_TailRun26:	equ	(ptr_TailMap_Run26-Map_Tails)/2	; 39
fr_TailRun31:	equ	(ptr_TailMap_Run31-Map_Tails)/2	; 3A
fr_TailRun32:	equ	(ptr_TailMap_Run32-Map_Tails)/2	; 3B
fr_TailRun33:	equ	(ptr_TailMap_Run33-Map_Tails)/2	; 3C
fr_TailRun34:	equ	(ptr_TailMap_Run34-Map_Tails)/2	; 3D
fr_TailRun35:	equ	(ptr_TailMap_Run35-Map_Tails)/2	; 3E
fr_TailRun36:	equ	(ptr_TailMap_Run36-Map_Tails)/2	; 3F
fr_TailRun41:	equ	(ptr_TailMap_Run41-Map_Tails)/2	; 40
fr_TailRun42:	equ	(ptr_TailMap_Run42-Map_Tails)/2	; 41
fr_TailRun43:	equ	(ptr_TailMap_Run43-Map_Tails)/2	; 42
fr_TailRun44:	equ	(ptr_TailMap_Run44-Map_Tails)/2	; 43
fr_TailRun45:	equ	(ptr_TailMap_Run45-Map_Tails)/2	; 44
fr_TailRun46:	equ	(ptr_TailMap_Run46-Map_Tails)/2	; 45
fr_TailRoll1:	equ	(ptr_TailMap_Roll1-Map_Tails)/2	; 46
fr_TailRoll2:	equ	(ptr_TailMap_Roll2-Map_Tails)/2	; 47
fr_TailRoll3:	equ	(ptr_TailMap_Roll3-Map_Tails)/2	; 48
fr_TailSpring1:	equ	(ptr_TailMap_Spring1-Map_Tails)/2	; 59
fr_TailSpring2:	equ	(ptr_TailMap_Spring2-Map_Tails)/2	; 5A
fr_TailDuck:	equ	(ptr_TailMap_Duck-Map_Tails)/2	; 5B
fr_TailHurt:	equ	(ptr_TailMap_Hurt-Map_Tails)/2	; 5C
fr_TailDeath:	equ	(ptr_TailMap_Death-Map_Tails)/2	; 5D
fr_TailFly1:	equ	(ptr_TailMap_Fly1-Map_Tails)/2	; 5E
fr_TailFly2:	equ	(ptr_TailMap_Fly2-Map_Tails)/2	; 5F
fr_TailSpindash1:	equ	(ptr_TailMap_Spindash1-Map_Tails)/2	; 60
fr_TailSpindash2:	equ	(ptr_TailMap_Spindash2-Map_Tails)/2	; 61
fr_TailSpindash3:	equ	(ptr_TailMap_Spindash3-Map_Tails)/2	; 62
fr_TailPush1:	equ	(ptr_TailMap_Push1-Map_Tails)/2	; 63
fr_TailPush2:	equ	(ptr_TailMap_Push2-Map_Tails)/2	; 64
fr_TailPush3:	equ	(ptr_TailMap_Push3-Map_Tails)/2	; 65
fr_TailPush4:	equ	(ptr_TailMap_Push4-Map_Tails)/2	; 66
fr_TailStop1:	equ	(ptr_TailMap_Stop1-Map_Tails)/2	; 67
fr_TailStop2:	equ	(ptr_TailMap_Stop2-Map_Tails)/2	; 68
fr_TailBalance1:	equ	(ptr_TailMap_Balance1-Map_Tails)/2	; 69
fr_TailBalance2:	equ	(ptr_TailMap_Balance2-Map_Tails)/2	; 6A
fr_TailWaterSlide:	equ	(ptr_TailMap_WaterSlide-Map_Tails)/2	; 6B
fr_TailHang1:	equ	(ptr_TailMap_Hang1-Map_Tails)/2	; 6C
fr_TailHang2:	equ	(ptr_TailMap_Hang2-Map_Tails)/2	; 6D
fr_TailFloat1:	equ	(ptr_TailMap_Float1-Map_Tails)/2	; 6E
fr_TailFloat2:	equ	(ptr_TailMap_Float2-Map_Tails)/2	; 6F
fr_TailFloat3:	equ	(ptr_TailMap_Float3-Map_Tails)/2	; 70
fr_TailFloat4:	equ	(ptr_TailMap_Float4-Map_Tails)/2	; 71
fr_TailFloat5:	equ	(ptr_TailMap_Float5-Map_Tails)/2	; 72
fr_TailFloat6:	equ	(ptr_TailMap_Float6-Map_Tails)/2	; 73
fr_TailGetAir:	equ	(ptr_TailMap_GetAir-Map_Tails)/2	; 74
fr_TailFlyTired1:	equ	(ptr_TailMap_FlyTired1-Map_Tails)/2	; 8E
fr_TailFlyTired2:	equ	(ptr_TailMap_FlyTired2-Map_Tails)/2	; 8F
fr_TailSwim1:	equ	(ptr_TailMap_Swim1-Map_Tails)/2	; 90
fr_TailSwim2:	equ	(ptr_TailMap_Swim2-Map_Tails)/2	; 91
fr_TailSwim3:	equ	(ptr_TailMap_Swim3-Map_Tails)/2	; 92
fr_TailSwim4:	equ	(ptr_TailMap_Swim4-Map_Tails)/2	; 93
fr_TailSwim5:	equ	(ptr_TailMap_Swim5-Map_Tails)/2	; 94
fr_TailSwimTired1:	equ	(ptr_TailMap_SwimTired1-Map_Tails)/2	; 95
fr_TailSwimTired2:	equ	(ptr_TailMap_SwimTired2-Map_Tails)/2	; 96
fr_TailSwimTired3:	equ	(ptr_TailMap_SwimTired3-Map_Tails)/2	; 97